/* GENERATED by desktop/tools/fetch-fonts.py - do not edit by hand.
   Maps Material Symbols icon names to glyphs of the subset font. */
export const ICON_GLYPHS = {
  add: '\u{e145}',
  close: '\u{e5cd}',
  arrow_back: '\u{e5c4}',
  arrow_forward: '\u{e5c8}',
  refresh: '\u{e5d5}',
  search: '\u{ef7a}',
  shield: '\u{e9e0}',
  more_vert: '\u{e5d4}',
  public: '\u{e80b}',
  workspaces: '\u{ea0f}',
  terminal: '\u{eb8e}',
  key: '\u{e73c}',
  settings: '\u{e8b8}',
  history: '\u{e8b3}',
  download: '\u{f090}',
  extension: '\u{e87b}',
  chevron_left: '\u{e5cb}',
  chevron_right: '\u{e5cc}',
} as const

export type IconName = keyof typeof ICON_GLYPHS
